#!/bin/bash
# Usage: ./install_evilginx.sh <domain> <public_ip>

# ==== CONFIG ====
RELEASE_URL="https://github.com/kgretzky/evilginx2/releases/download/v3.3.0/evilginx-v3.3.0-linux-64bit.zip"
INSTALL_DIR="evilginx"
RELEASE_FILE="evilginx-linux.zip"
BINARY_NAME="evilginx"

# ==== FUNCTIONS ====
error_exit() {
    echo "[!] $1"
    exit 1
}

cleanup() {
    if [[ -n $EVILGINX_PID ]] && kill -0 $EVILGINX_PID 2>/dev/null; then
        echo "[*] Stopping Evilginx..."
        kill $EVILGINX_PID
        wait $EVILGINX_PID 2>/dev/null
    fi
}

# Set trap for cleanup
trap cleanup EXIT

# ==== ARGUMENT CHECK ====
if [ $# -ne 2 ]; then
    echo "Usage: $0 <domain> <public_ip>"
    exit 1
fi

DOMAIN=$1
PUBLIC_IP=$2

# ==== CHANGE TO SCRIPT DIRECTORY ====
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
echo "[*] Script location: $SCRIPT_DIR"
cd "$SCRIPT_DIR" || error_exit "Failed to change to script directory."

# ==== CHECK IF ALREADY INSTALLED ====
if [[ -f "$INSTALL_DIR/$BINARY_NAME" ]]; then
    echo "[!] Evilginx seems to already be installed. Remove $INSTALL_DIR first if you want a fresh install."
    exit 1
fi

# ==== CREATE DIRECTORY ====
echo "[*] Creating install directory: $INSTALL_DIR"
mkdir -p "$INSTALL_DIR" || error_exit "Failed to create directory."
cd "$INSTALL_DIR" || error_exit "Failed to enter install directory."

# ==== DOWNLOAD RELEASE ====
echo "[*] Downloading Evilginx release..."
wget -q --show-progress "$RELEASE_URL" -O "$RELEASE_FILE" || error_exit "Download failed."

# ==== VERIFY DOWNLOAD ====
if [ ! -f "$RELEASE_FILE" ]; then
    error_exit "Release file not found after download."
fi

# ==== UNZIP ====
echo "[*] Extracting release..."
unzip -o "$RELEASE_FILE" || error_exit "Failed to unzip release."

# ==== MAKE EXECUTABLE ====
chmod +x "$BINARY_NAME" || error_exit "Failed to make binary executable."

# ==== VERIFY BINARY WORKS ====
echo "[*] Testing Evilginx binary..."
if ! ./"$BINARY_NAME" --help >/dev/null 2>&1; then
    error_exit "Evilginx binary is not working properly."
fi

# ==== CREATE CONFIG FILE ====
echo "[*] Creating Evilginx configuration file..."

# Create the config directory if it doesn't exist
mkdir -p config

# Create config.yaml with the provided domain and IP
cat > config/config.yaml << EOF
# Evilginx Configuration
# Generated by install script

# Server configuration
server_bind_ip: "0.0.0.0"
server_bind_port: 443
server_bind_ip_http: "0.0.0.0" 
server_bind_port_http: 80

# DNS configuration
dns_bind_ip: "0.0.0.0"
dns_bind_port: 53

# External configuration
external_ipv4: "$PUBLIC_IP"
base_domain: "$DOMAIN"

# Certificate configuration
autocert: true
autocert_dir: "./certs"

# Phishlets configuration
phishlets_dir: "./phishlets"
redirectors_dir: "./redirectors"

# Database
database_path: "./data.db"

# Logging
log_file: "./evilginx.log"
log_level: "info"
EOF

echo "[*] Configuration file created: config/config.yaml"

echo "[+] Evilginx installed and configured!"
echo "    Domain: $DOMAIN"
echo "    Public IP: $PUBLIC_IP"
echo "    Config: $CONFIG_DIR/config.yaml"
echo
echo "To resolve DNS port conflict (common issue):"
echo "  sudo systemctl stop systemd-resolved"
echo
echo "Run it with: cd $INSTALL_DIR && sudo ./$BINARY_NAME"
exit 0
